version: '2'
services:
  python:
    image: kammana/python-redis:1.0
    container_name: python
    ports:
     - "8080:5000"
    networks:
      - javahome-app
  redis:
    container_name: redis
    image: "redis"
    networks:
      - javahome-app
networks:
  javahome-app:
    driver: bridge
